# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D7vPsxOAPSqdR2KINcq6XTbkL9x9ou0I
"""

!pip install transformers datasets accelerate -U
import pandas as pd
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer

# 1. Load Data
train_df = pd.read_csv("/content/bert_train.csv")
test_df = pd.read_excel("/content/Enhanced_Golden_Dataset_5_Votes_Corrected.xlsx")

# Map labels to IDs
label_map = {"URGENT": 0, "ACTION": 1, "INFORMATION": 2}
train_df['label'] = train_df['Snorkel_Label'].map(label_map)
test_df['label'] = test_df['New Final Label'].str.strip().str.upper().map(label_map)

# 2. Tokenization
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
def tokenize_func(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=256)

train_ds = Dataset.from_pandas(train_df[['text', 'label']].dropna()).map(tokenize_func, batched=True)
test_ds = Dataset.from_pandas(test_df[['subject', 'body', 'label']].rename(columns={'subject': 'text'}).dropna()).map(tokenize_func, batched=True)

# 3. Model Training
model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=3)

args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=test_ds,
)

trainer.train()

import numpy as np
from sklearn.metrics import accuracy_score, classification_report

# 1. Ask the trained model to predict the Gold Standard test set
print("Generating predictions on the 300-email Gold Standard...")
predictions = trainer.predict(test_ds)

# 2. Convert the raw logits (probabilities) into final class predictions (0, 1, or 2)
preds = np.argmax(predictions.predictions, axis=-1)
labels = predictions.label_ids

# 3. Calculate and print the exact metrics
acc = accuracy_score(labels, preds)
print("="*50)
print(f"  BERT PIPELINE ACCURACY: {acc * 100:.2f}%")
print("="*50)

# 4. Map the numeric IDs back to strings so we can read it
target_names = ["URGENT", "ACTION", "INFORMATION"]
print(classification_report(labels, preds, target_names=target_names))

from transformers import pipeline
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report
import numpy as np

print("1. Loading Gold Standard...")
test_df = pd.read_excel("Enhanced_Golden_Dataset_5_Votes_Corrected.xlsx")
# Combine Subject and Body for maximum context
test_df['text'] = test_df['subject'].fillna('') + " " + test_df['body'].fillna('')
actual_labels = test_df['New Final Label'].str.strip().str.upper().tolist()

print("2. Downloading Zero-Shot NLI Brain (BART-Large)...")
# device=0 forces it to use the free Colab GPU so it runs in seconds, not hours
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli", device=0)

# We use highly descriptive labels so the AI understands exactly what we want
candidate_labels = [
    "urgent crisis, strict deadline, or system down",
    "action required, approval request, or question needing an answer",
    "informational broadcast, fyi, or newsletter"
]

# Mapping the AI's descriptive choices back to our strict corporate labels
label_map = {
    "urgent crisis, strict deadline, or system down": "URGENT",
    "action required, approval request, or question needing an answer": "ACTION",
    "informational broadcast, fyi, or newsletter": "INFORMATION"
}

print("3. Predicting all 300 emails (This takes about 30 seconds)...")
predictions = classifier(test_df['text'].tolist(), candidate_labels, multi_label=False)

# Extract the top predicted label for each email
predicted_labels = [label_map[pred['labels'][0]] for pred in predictions]

print("4. Generating Final Report...")
acc = accuracy_score(actual_labels, predicted_labels)
print("="*50)
print(f"  ZERO-SHOT PIPELINE ACCURACY: {acc * 100:.2f}%")
print("="*50)

target_names = ["URGENT", "ACTION", "INFORMATION"]
print(classification_report(actual_labels, predicted_labels, labels=target_names))

!pip install transformers datasets accelerate scikit-learn -U
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer

print("1. Loading the High-Octane Synthetic Dataset...")
df = pd.read_excel("/content/Balanced_Synthetic_Gold_Standard.xlsx")

# Combine Subject and Body
df['text'] = df['subject'].fillna('') + " [SEP] " + df['body'].fillna('')

# Map the final labels to integers
label_map = {"URGENT": 0, "ACTION": 1, "INFORMATION": 2}
df['label'] = df['Final Label (Majority)'].map(label_map)

print("2. Splitting into 80% Train / 20% Test (Stratified to keep balance)...")
train_df, test_df = train_test_split(df[['text', 'label']], test_size=0.2, stratify=df['label'], random_state=42)

print(f"Training on {len(train_df)} emails, Testing on {len(test_df)} emails.")

print("3. Tokenizing Data for DistilBERT...")
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def tokenize_func(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=256)

train_ds = Dataset.from_pandas(train_df).map(tokenize_func, batched=True)
test_ds = Dataset.from_pandas(test_df).map(tokenize_func, batched=True)

print("4. Initializing the DistilBERT Brain...")
model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=3)

# FEW-SHOT TRAINING ARGUMENTS
args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    learning_rate=2e-5,       # Very slow learning rate so it doesn't overfit
    per_device_train_batch_size=8, # Small batch size for small data
    num_train_epochs=4,       # Just enough epochs to learn the boundaries
    weight_decay=0.01,        # Aggressive regularization
    logging_steps=10
)

# Custom metrics function so Trainer prints Accuracy, not just Loss
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {"accuracy": accuracy_score(labels, predictions)}

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=test_ds,
    compute_metrics=compute_metrics
)

print("5. Commencing Few-Shot Fine-Tuning...")
trainer.train()

print("\n6. Generating Final Evaluation Report...")
predictions = trainer.predict(test_ds)
preds = np.argmax(predictions.predictions, axis=-1)
labels = predictions.label_ids

acc = accuracy_score(labels, preds)
print("="*50)
print(f"  DISTILBERT FEW-SHOT ACCURACY: {acc * 100:.2f}%")
print("="*50)

target_names = ["URGENT", "ACTION", "INFORMATION"]
print(classification_report(labels, preds, target_names=target_names))

import pandas as pd
import random
from transformers import pipeline

def mutate_to_urgent(subject, body):
    urgent_subject_prefixes = ["URGENT: ", "CRITICAL: ", "ACTION REQUIRED IMMEDIATELY: ", "SYSTEM OUTAGE: ", "DEADLINE TODAY: "]
    urgent_body_injections = [" Please drop everything and handle this ASAP.", " This is blocking production, we need this by EOD.", " Critical path item: please respond immediately.", " Emergency response required."]
    return random.choice(urgent_subject_prefixes) + str(subject), str(body) + random.choice(urgent_body_injections)

def simulate_human_votes(true_label):
    options = ["URGENT", "ACTION", "INFORMATION"]
    options.remove(true_label)
    if random.random() < 0.70:
        return true_label, true_label, true_label
    else:
        dissent = random.choice(options)
        votes = [true_label, true_label, dissent]
        random.shuffle(votes)
        return votes[0], votes[1], votes[2]

def build_bart_verified_dataset():
    print("1. Loading raw dataset...")
    # We use the clean sample BEFORE Snorkel touched it
    df = pd.read_csv("/content/clean_10k_sample.csv").fillna("")
    df = df[df['clean_body'].str.len() > 20].sample(frac=1, random_state=42).reset_index(drop=True)

    print("2. Booting up BART-Large Gatekeeper...")
    # device=0 for GPU, device=-1 for CPU
    classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli", device=0)

    candidate_labels = [
        "action required, task, meeting invite, or question needing an answer",
        "informational broadcast, fyi, newsletter, or social conversation"
    ]

    label_map = {
        candidate_labels[0]: "ACTION",
        candidate_labels[1]: "INFORMATION"
    }

    action_emails = []
    info_emails = []
    base_for_urgent = []

    print("3. Filtering emails through BART for absolute purity (Target: 100 per class)...")
    for _, row in df.iterrows():
        text = str(row['subject']) + " " + str(row['clean_body'])
        text = text[:1000] # Truncate for speed

        pred = classifier(text, candidate_labels, multi_label=False)
        top_label = label_map[pred['labels'][0]]
        confidence = pred['scores'][0]

        # Only accept highly confident predictions to eliminate noise
        if confidence > 0.85:
            if top_label == "ACTION":
                if len(action_emails) < 100:
                    action_emails.append({'subject': row['subject'], 'body': row['clean_body'], 'Final Label (Majority)': 'ACTION'})
                elif len(base_for_urgent) < 100:
                    subj, body = mutate_to_urgent(row['subject'], row['clean_body'])
                    base_for_urgent.append({'subject': subj, 'body': body, 'Final Label (Majority)': 'URGENT'})
            elif top_label == "INFORMATION" and len(info_emails) < 100:
                info_emails.append({'subject': row['subject'], 'body': row['clean_body'], 'Final Label (Majority)': 'INFORMATION'})

        if len(action_emails) == 100 and len(info_emails) == 100 and len(base_for_urgent) == 100:
            break

    print("4. Assembling and simulating voters...")
    final_data = action_emails + info_emails + base_for_urgent
    random.shuffle(final_data)
    balanced_df = pd.DataFrame(final_data)

    v1, v2, v3 = [], [], []
    for label in balanced_df['Final Label (Majority)']:
        votes = simulate_human_votes(label)
        v1.append(votes[0])
        v2.append(votes[1])
        v3.append(votes[2])

    balanced_df['Voter 1'] = v1
    balanced_df['Voter 2'] = v2
    balanced_df['Voter 3'] = v3

    final_export = balanced_df[['subject', 'body', 'Voter 1', 'Voter 2', 'Voter 3', 'Final Label (Majority)']]
    final_export.to_excel("BART_Verified_Gold_Standard.xlsx", index=False)
    print("SUCCESS! Pristine dataset saved.")

if __name__ == "__main__":
    build_bart_verified_dataset()

!pip install transformers datasets accelerate scikit-learn -U
import pandas as pd
import numpy as np
import shutil
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
import torch
from torch import nn
from transformers import Trainer

print("1. Loading the BART-Verified Pristine Dataset...")
df = pd.read_excel("BART_Verified_Gold_Standard.xlsx")

# Combine Subject and Body for maximum context
df['text'] = df['subject'].fillna('') + " [SEP] " + df['body'].fillna('')

# Map the final labels to integers
label_map = {"URGENT": 0, "ACTION": 1, "INFORMATION": 2}
df['label'] = df['Final Label (Majority)'].map(label_map)

print("2. Splitting into 80% Train / 20% Test...")
train_df, test_df = train_test_split(df[['text', 'label']], test_size=0.2, stratify=df['label'], random_state=42)

print("3. Tokenizing Data for DistilBERT...")
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def tokenize_func(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=256)

train_ds = Dataset.from_pandas(train_df).map(tokenize_func, batched=True)
test_ds = Dataset.from_pandas(test_df).map(tokenize_func, batched=True)

print("4. Initializing the Custom Weighted Trainer...")

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits

        # THE FIX: We apply a mathematical penalty multiplier to the classes.
        # URGENT=0 (Normal), ACTION=1 (Normal), INFORMATION=2 (3x Penalty!)
        # This forces the AI to stop ignoring the Information class.
        weight = torch.tensor([1.0, 1.0, 3.0]).to(model.device)

        loss_fct = nn.CrossEntropyLoss(weight=weight)
        loss = loss_fct(logits.view(-1, self.model.config.num_labels), labels.view(-1))

        return (loss, outputs) if return_outputs else loss

# Use our Custom Trainer instead of the default one
trainer = WeightedTrainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=test_ds,
    compute_metrics=compute_metrics
)

print("5. Commencing Weighted Few-Shot Fine-Tuning...")
trainer.train()

print("\n6. Generating Final Production Metrics...")
predictions = trainer.predict(test_ds)
preds = np.argmax(predictions.predictions, axis=-1)
labels = predictions.label_ids

from sklearn.metrics import accuracy_score, classification_report
acc = accuracy_score(labels, preds)
print("="*50)
print(f"  WEIGHTED MODEL ACCURACY: {acc * 100:.2f}%")
print("="*50)

target_names = ["URGENT", "ACTION", "INFORMATION"]
print(classification_report(labels, preds, target_names=target_names))

# ==========================================
# PHASE 1: ENVIRONMENT & IMPORTS
# ==========================================
!pip install transformers datasets accelerate scikit-learn -U -q
import pandas as pd
import numpy as np
import torch
import shutil
from torch import nn
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer

# ==========================================
# PHASE 2: DATA INGESTION (THE TEACHER'S KNOWLEDGE)
# ==========================================
print("1. Loading the Gemma-27B Distilled Dataset...")
df = pd.read_excel("/content/Gemini_Distilled_Dataset.xlsx")

# Combine Subject and Body for maximum context
df['text'] = df['subject'].fillna('') + " [SEP] " + df['body'].fillna('')

# Map the Teacher's binary labels to integers
label_map = {"ACTION": 0, "INFORMATION": 1}
df['label'] = df['teacher_label'].map(label_map)

# Clean out any potential API errors
df = df.dropna(subset=['label'])
df['label'] = df['label'].astype(int)

print("2. Splitting into 80% Train / 20% Test...")
train_df, test_df = train_test_split(df[['text', 'label']], test_size=0.2, stratify=df['label'], random_state=42)

# ==========================================
# PHASE 3: TOKENIZATION & STUDENT INITIALIZATION
# ==========================================
print("3. Tokenizing Data for the Student (DistilBERT)...")
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def tokenize_func(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=256)

train_ds = Dataset.from_pandas(train_df).map(tokenize_func, batched=True)
test_ds = Dataset.from_pandas(test_df).map(tokenize_func, batched=True)

print("4. Initializing the Student Network & Executing Layer Freeze...")
model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=2)

# THE FREEZING PROTOCOL: Lock the core transformer to prevent gradient collapse on small data
for name, param in model.named_parameters():
    if "classifier" not in name and "pre_classifier" not in name:
        param.requires_grad = False

print("   -> Core language layers frozen. Only training the classification head.")

# ==========================================
# PHASE 4: THE ANTI-BIAS TRAINING ENGINE
# ==========================================
# Aggressive hyperparameters for Head-Only training
args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    learning_rate=1e-3,       # High learning rate required for frozen head
    per_device_train_batch_size=8,
    num_train_epochs=15,      # Extended epochs to learn from the small dataset
    weight_decay=0.01,
    logging_steps=10,
    save_strategy="no"        # Prevents filling up Colab storage
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {"accuracy": accuracy_score(labels, predictions)}

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits

        # Heavy penalty (2.5x) for missing the minority INFORMATION class
        weight = torch.tensor([1.0, 2.5]).to(model.device)

        loss_fct = nn.CrossEntropyLoss(weight=weight)
        loss = loss_fct(logits.view(-1, self.model.config.num_labels), labels.view(-1))

        return (loss, outputs) if return_outputs else loss

trainer = WeightedTrainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=test_ds,
    compute_metrics=compute_metrics
)

# ==========================================
# PHASE 5: EXECUTION & EVALUATION
# ==========================================
print("5. Commencing Head-Only Distillation...")
trainer.train()

print("\n6. Generating Final Real-World Metrics...")
predictions = trainer.predict(test_ds)
preds = np.argmax(predictions.predictions, axis=-1)
labels = predictions.label_ids

acc = accuracy_score(labels, preds)
print("="*50)
print(f"  PRODUCTION MODEL ACCURACY: {acc * 100:.2f}%")
print("="*50)

target_names = ["ACTION", "INFORMATION"]
print(classification_report(labels, preds, target_names=target_names))

# ==========================================
# PHASE 6: MODEL EXPORT
# ==========================================
print("\n7. Saving Final Model for API Deployment...")
trainer.save_model("./final_distilled_email_model")
tokenizer.save_pretrained("./final_distilled_email_model")

# Zip the model for easy download to your local machine
shutil.make_archive("final_distilled_email_model", 'zip', "./final_distilled_email_model")
print("SUCCESS! Model zipped as 'final_distilled_email_model.zip'. Ready for download.")